# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appserv_name', models.CharField(max_length=200)),
                ('appserv_desc', models.CharField(max_length=200)),
                ('appserv_active', models.IntegerField(default=0)),
                ('appserv_support_group', models.CharField(max_length=200)),
                ('appserv_department', models.CharField(max_length=200)),
                ('appserv_availability', models.CharField(max_length=200)),
                ('appserv_team_member', models.CharField(max_length=200)),
                ('appserv_business_owner', models.CharField(max_length=200)),
            ],
        ),
    ]
