# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alloc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('app_dept', models.CharField(max_length=200)),
                ('app_sla', models.CharField(max_length=200)),
                ('app_primary', models.CharField(max_length=200)),
                ('app_secondary', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Secondary',
            new_name='Person',
        ),
        migrations.DeleteModel(
            name='Appname',
        ),
        migrations.DeleteModel(
            name='Primary',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_text',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='secondary_text',
            new_name='person_name',
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloc.Department'),
        ),
        migrations.AddField(
            model_name='application',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloc.Person'),
        ),
        migrations.AddField(
            model_name='application',
            name='sla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloc.SLA'),
        ),
    ]
