# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alloc', '0002_auto_20160113_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='department',
        ),
        migrations.RemoveField(
            model_name='application',
            name='person',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sla',
        ),
        migrations.AlterField(
            model_name='application',
            name='app_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloc.Department'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='alloc.Person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_secondary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='alloc.Person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_sla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloc.SLA'),
        ),
    ]
